<a href="https://colab.research.google.com/github/NinaKhapko/Numpy_solutions.ipynb/blob/main/Numpy_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hi')

hi


In [ ]:
import numpy as np

In [ ]:
np.array( [0]*10 )

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.array( [1]*10 )

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.array( [5]*10 )

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
N=50
print(list(range(10, N+1)))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [ ]:
array=np.arange(10,50,2)
print(array) 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
m = np.arange(0,9).reshape(3,3)
np.reshape
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import random
random.uniform(0, 1)

0.2901850895964364

In [ ]:
rand_num = np.random.normal(0,1,25)
print(rand_num)

[ 0.31588513  0.99127371  1.26867917 -0.86199098  0.97580135 -1.35398697
  1.11852677  0.04200368  1.73696915  1.3370623  -1.30150358  0.32449882
  0.54385529 -0.24654159  0.91396928 -1.25762342  1.95522571  0.04226485
  0.2317668   0.10374816 -0.20176131 -0.43630829  1.02394473 -0.27853198
  0.61490161]


In [ ]:
m = np.arange(0.01,1.01,0.01).reshape(10,10)
np.reshape
m

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('-----------------')
res = mat[2:2+5, 1:1+5]
print(res)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-----------------
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
print(mat[3][4])

20


In [ ]:
print(mat[0:0+3, 1:2])

[[ 2]
 [ 7]
 [12]]


In [ ]:
print(mat[4:4+5, 0:])

[[21 22 23 24 25]]


In [ ]:
print(mat[3:3+5, 0:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
a= np.sum(mat)
print(a)

325


In [ ]:
b = np.std(mat)
print(b)

7.211102550927978


In [ ]:
c=mat.sum(axis=0)
print(c)

[55 60 65 70 75]
